### ISSUE TITLE
Installation/build failure with LuaRocks on Lua 5.3.3 due to outdated dependency "luabitop"

### ISSUE THREAD

**Issue by JoshuaS3** [leafo/pgmoon#95]
Attempting an install with `sudo luarocks install pgmoon` (originally attempted install of Lapis with pgmoon as a dependency):

```
pgmoon 1.11.0-1 depends on luabitop (not installed)
Installing https://luarocks.org/luabitop-1.0.1-1.src.rock
Do not use 'module' as a build type. Use 'builtin' instead.
gcc -O2 -fPIC -I/usr/include/lua5.3 -c bit.c -o bit.o
bit.c: In function ‘barg’:
bit.c:79:2: error: #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
   79 | #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
      |  ^~~~~
bit.c:82:5: warning: implicit declaration of function ‘luaL_typerror’; did you mean ‘luaL_error’? [-Wimplicit-function-declaration]
   82 |     luaL_typerror(L, idx, "number");
      |     ^~~~~~~~~~~~~
      |     luaL_error
bit.c: In function ‘luaopen_bit’:
bit.c:175:3: warning: implicit declaration of function ‘luaL_register’; did you mean ‘lua_register’? [-Wimplicit-function-declaration]
  175 |   luaL_register(L, "bit", bit_funcs);
      |   ^~~~~~~~~~~~~
      |   lua_register

Error: Failed installing dependency: https://luarocks.org/luabitop-1.0.1-1.src.rock - Build error: Failed compiling object bit.o
```

for Lua 5.3.3. Seems like bitop only works on Lua 5.1-5.2. Looks like luarocks also tries to install `1.0.1-1` instead of `1.0.2-3`, for whatever reason.

One can only hope Mike Pall will come back and bring his projects up to date :^)

**Comment by JoshuaS3** [comment]
could be solved/avoided by updating the rockspec's dependency versions (namely constrain Lua to 5.1-5.2). This could be done for both pgmoon and Lapis.
